---
name: "Conventional Commits Next Version"
description: "Get the next version based on conventional commits"
inputs:
  calculation-mode:
    description: "Calculation mode"
    required: false
    default: "Batch"
  from-version:
    description: "From version"
    required: true
  from-reference:
    description: "From reference"
    required: true
outputs:
  next-version:
    description: "The next version"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.calculation-mode }}
    - ${{ inputs.from-version }}
    - ${{ inputs.from-reference }}
